### ISSUE TITLE
Feature request: provide support for non-program commands

### ISSUE THREAD

**Issue by suhail-singh** [andykuszyk/noman.el#3]
On Linux, some commands such as `type` do support `--help`, however invoking
`noman` with `type` results in

```
Searching for program: No such file or directory, type
```

It would be helpful if `noman` would be able to provide the kind of output that
one gets by doing `M-! type --help`.

**Comment by andykuszyk** [comment]
I see what you mean, but the trouble is that `type` is a built-in command of a shell. How would noman know that you were not trying to run a program?

I suppose it could run all the commands given to `M-x noman` in a shell?
