### ISSUE TITLE
Help for git command works poorly.

### ISSUE THREAD

**Issue by Dale-M** [andykuszyk/noman.el#5]
`M-x noman<ret>git<ret>` presents the top-level help nicely, and clicking one of the sub-commands, for example, `clone`, pulls up a man page for that sub-command.  But then clicking another sub-command, like `rm`, produces an empty page.  This persists; the only way out is to close all the 'noman' buffers, and start again at the top-level.

**Comment by andykuszyk** [comment]
@Dale-M thanks for taking the time to submit an issue :pray: 

I think this issue has been solved in the latest release. Please could you pull the latest code, and let me know if it's still a problem?

**Comment by Dale-M** [comment]
That works very nicely, thank you.  I'll see if I can get it into the Guix system for you.
